version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    
  streamlit:
    build: .
    ports:
      - "8505:8505"
    depends_on:
      - elasticsearch